
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  creationTimestamp: null
  name: blockdevices.longhorn.io
spec:
  group: longhorn.io
  names:
    kind: BlockDevice
    listKind: BlockDeviceList
    plural: blockdevices
    shortNames:
    - bd
    singular: blockdevice
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.nodeName
      name: NodeName
      type: string
    - jsonPath: .status.state
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: BlockDevice is the schema to describe a node block device
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              capacity:
                description: a object describe the disk capacity
                properties:
                  physicalBlockSizeBytes:
                    description: the size of the physical blocks used on the disk,
                      in bytes
                    format: int64
                    type: integer
                  sizeBytes:
                    description: the amount of storage the disk provides
                    format: int64
                    type: integer
                required:
                - physicalBlockSizeBytes
                - sizeBytes
                type: object
              details:
                description: a object describe the disk details
                properties:
                  busPath:
                    description: a string represents the block device bus path
                    type: string
                  driveType:
                    description: a string represents the type of drive bus, options
                      are "HDD", "FDD", "ODD", or "SSD", which correspond to a hard
                      disk drive (rotational), floppy drive, optical (CD/DVD) drive
                      and solid-state drive.
                    enum:
                    - HDD
                    - FDD
                    - ODD
                    - SSD
                    - Unknown
                    - ""
                    type: string
                  isRemovable:
                    description: contains a boolean indicating if the disk drive is
                      removable
                    type: boolean
                  model:
                    description: a string with the vendor-assigned disk model name
                    type: string
                  numaNodeID:
                    description: the numeric index of the NUMA node this disk is local
                      to, or -1
                    type: integer
                  serialNumber:
                    description: a string with the disk's serial number
                    type: string
                  storageController:
                    description: the type of storage controller/drive, options are
                      "SCSI", "IDE", "virtio", "MMC", or "NVMe"
                    enum:
                    - SCSI
                    - IDE
                    - virtio
                    - MMC
                    - NVMe
                    - Unknown
                    - ""
                    type: string
                  vendor:
                    description: a string with the name of the hardware vendor for
                      the disk drive
                    type: string
                  wwn:
                    description: a string with the disk's World Wide Name(WWN)
                    type: string
                required:
                - busPath
                - driveType
                - isRemovable
                - model
                - numaNodeID
                - serialNumber
                - storageController
                - vendor
                - wwn
                type: object
              name:
                description: a string with the short name of the disk, e.g. "sda"
                type: string
              nodeName:
                description: a Node struct, describe the node details the BD is attached
                  to
                type: string
              partitions:
                description: contains an array of Partition structs, one for each
                  partition on the disk
                items:
                  properties:
                    isReadOnly:
                      description: a bool indicating the partition is read-only
                      type: boolean
                    label:
                      type: string
                    mountPoint:
                      description: a string with the partition's mount point, or ""
                        if no mount point was discovered
                      type: string
                    name:
                      description: a string with the short name of the partition,
                        e.g. "sda1".
                      type: string
                    sizeBytes:
                      description: contains the amount of storage the partition provides.
                      format: int64
                      type: integer
                    type:
                      description: a string indicated the filesystem type for the
                        partition, or "" if the system could not determine the type.
                      type: string
                    uuid:
                      description: a string containing the volume UUID on Linux, the
                        partition UUID on MacOS and nothing on Windows.
                      type: string
                  required:
                  - isReadOnly
                  - label
                  - mountPoint
                  - name
                  - sizeBytes
                  - type
                  - uuid
                  type: object
                type: array
            required:
            - capacity
            - details
            - name
            - nodeName
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              state:
                description: the current state of the block device, options are "Active",
                  "Inactive", or "Unknown"
                enum:
                - Active
                - Inactive
                - Unknown
                type: string
            type: object
        required:
        - spec
        - status
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
