
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  creationTimestamp: null
  name: nodes.longhorn.io
spec:
  group: longhorn.io
  names:
    kind: Node
    listKind: NodeList
    plural: nodes
    singular: node
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              allowScheduling:
                type: boolean
              disks:
                additionalProperties:
                  properties:
                    allowScheduling:
                      type: boolean
                    evictionRequested:
                      type: boolean
                    path:
                      type: string
                    storageReserved:
                      format: int64
                      type: integer
                    tags:
                      items:
                        type: string
                      type: array
                  required:
                  - allowScheduling
                  - evictionRequested
                  - path
                  - storageReserved
                  - tags
                  type: object
                type: object
              engineManagerCPURequest:
                type: integer
              evictionRequested:
                type: boolean
              name:
                type: string
              replicaManagerCPURequest:
                type: integer
              tags:
                items:
                  type: string
                type: array
            required:
            - allowScheduling
            - disks
            - engineManagerCPURequest
            - evictionRequested
            - name
            - replicaManagerCPURequest
            - tags
            type: object
          status:
            properties:
              conditions:
                additionalProperties:
                  properties:
                    lastProbeTime:
                      type: string
                    lastTransitionTime:
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastProbeTime
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: object
              diskStatus:
                additionalProperties:
                  properties:
                    conditions:
                      additionalProperties:
                        properties:
                          lastProbeTime:
                            type: string
                          lastTransitionTime:
                            type: string
                          message:
                            type: string
                          reason:
                            type: string
                          status:
                            type: string
                          type:
                            type: string
                        required:
                        - lastProbeTime
                        - lastTransitionTime
                        - message
                        - reason
                        - status
                        - type
                        type: object
                      type: object
                    diskUUID:
                      type: string
                    scheduledReplica:
                      additionalProperties:
                        format: int64
                        type: integer
                      type: object
                    storageAvailable:
                      format: int64
                      type: integer
                    storageMaximum:
                      format: int64
                      type: integer
                    storageScheduled:
                      format: int64
                      type: integer
                  required:
                  - conditions
                  - diskUUID
                  - scheduledReplica
                  - storageAvailable
                  - storageMaximum
                  - storageScheduled
                  type: object
                type: object
              region:
                type: string
              zone:
                type: string
            required:
            - conditions
            - diskStatus
            - region
            - zone
            type: object
        required:
        - metadata
        - spec
        - status
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
